### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by ghost** [Aceba1/TerraTech-Mod-Manager-GTK#4]
Hey so bad way to contact you but I got my account suspended from discord, can you shoot me a dm on twitter? @ubuntu_20_04 also it's ubuntu from discord

**Comment by USMP-lancer** [comment]
not exactly the place to do this but whatever

**Comment by ghost** [comment]
god damn it, why did i write this
also, it was mostly directed at aceba but whatever
